apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: teamadb
  labels:
    app: teamadb
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: teamadb
  endpoints:
  - port: http
    path: /metrics
