apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-tenant
  labels:
    app: service-tenant
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: service-tenant
  endpoints:
  - port: http
    path: /metrics
